# Default values
replicaCount: 3
deploymentMetadata:
  name: hello  
image: nginxdemos/hello
targetPort: 80
port: 80    
serviceName: hello-svc
ingress:
  enabled: false
  className: nginx
  name: hello-ingress
  annotations: 
    ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ingress.class: nginx
  spec:
  ingressClassName: nginx  
  hosts:
    - host: test.com
      paths:
        - path: /
          pathType: Prefix          
autoscaling:
  enabled: false
  name: hello-scaling
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80